# Generated by Django 4.1.6 on 2023-02-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_user_email_userbio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbio',
            name='bio',
            field=models.CharField(default='bio', max_length=30),
        ),
        migrations.AlterField(
            model_name='userbio',
            name='bio_name',
            field=models.CharField(default='bio_name', max_length=20),
        ),
        migrations.AlterField(
            model_name='userbio',
            name='links',
            field=models.CharField(default='links', max_length=30),
        ),
    ]
