# Generated by Django 4.1.6 on 2023-02-06 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_uploads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploads',
            name='id',
        ),
        migrations.AddField(
            model_name='uploads',
            name='upload_id',
            field=models.BigAutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='user',
            name='liked',
            field=models.IntegerField(default=0, max_length=5),
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_likes', models.IntegerField(default=0)),
                ('uploads', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.uploads')),
            ],
        ),
    ]
