# Generated by Django 4.1.6 on 2023-02-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_uploads_id_uploads_upload_id_user_liked_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='upload_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
