# Generated by Django 4.1.6 on 2023-02-06 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_uploads_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='liked',
        ),
    ]
