# Generated by Django 4.1.6 on 2023-02-06 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_user_liked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploads',
            old_name='upload_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='uploads',
            name='liked',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
