# Generated by Django 4.1.6 on 2023-02-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_upload_id_uploads_id_remove_uploads_liked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
