# Generated by Django 4.1.6 on 2023-02-06 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_uploads_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploads',
            name='id',
        ),
        migrations.AddField(
            model_name='uploads',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploads',
            name='upload_id',
            field=models.BigAutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.uploads')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
