# Generated by Django 4.1.6 on 2023-02-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_uploads_upload_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='liked',
            field=models.IntegerField(default=0),
        ),
    ]
