# Generated by Django 4.1.6 on 2023-02-07 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_like_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='liked',
        ),
    ]
