# Generated by Django 4.1.6 on 2023-02-09 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio_uploads',
            fields=[
                ('upload_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('audio', models.FileField(upload_to='audio_uploads')),
                ('audio_name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
