# Generated by Django 4.1.6 on 2023-02-09 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_audio_uploads'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio_uploads',
            old_name='upload_id',
            new_name='audio_id',
        ),
    ]
