# Generated by Django 4.1.6 on 2023-02-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_rename_upload_id_audio_uploads_audio_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='premium',
            field=models.IntegerField(default=0),
        ),
    ]
